import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Artikel from "@/components/artikel";
import List from "@/components/list";
import Service from "@/components/service";
import Viwers from "@/components/viwers";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <List />
        <Service />
        <Artikel />
        <Viwers />
        <Footer />
      </body>
    </html>
  );
}
